schema_version = "1.0.0"
id = "dj_ik_fk_snapping_tool"
version = "0.1.0"
name = "Double Jointed IK-FK Snapping Tool"
tagline = "Tools to perform IK to FK and FK to IK snapping with added knees"
maintainer = "PixelTaku <BSKY: pixeltaku.bsky.social>"
type = "add-on"
website = "https://github.com/PixelTaku/Double_Jointed_IK-FK_Snapping_Tool"
tags = ["Animation", "Rigging"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2022 Byron Mallett", "2024 Endertainer007", "2025 PixelTaku"]
